name: build-game

# Controls when the workflow will run
on: [workflow_dispatch]

env:
  GODOT_ANDROID_KEYSTORE_RELEASE_PATH: ./android-export-variables.keystore
  GODOT_ANDROID_KEYSTORE_RELEASE_USER: user
  GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD: password

jobs:
  # job id, can be anything
  export_game:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    # Add permission for release creation. Can be made narrower according to your needs
    permissions: write-all
    # Job name, can be anything
    name: Export Game
    steps:
      # Always include the checkout step so that
      # your project is available for Godot to export
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    # - name: Fix build error
    #   run: mv ./android-export-variables.blank ./android-export-variables.keystore

    - name: Export game
      id: export
      # Use latest version (see releases for all versions)
      uses: firebelley/godot-export@v6.0.0
      with:
        # Defining all the required inputs
        godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.2.2-stable/Godot_v4.2.2-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.2.2-stable/Godot_v4.2.2-stable_export_templates.tpz
        relative_project_path: ./
        archive_output: true

    - name: Publish artifacts
      uses: actions/upload-artifact@v4
      with:
        name: archived-export
        path: ${{ steps.export.outputs.archive_directory }}/*

    #   # This release action has worked well for me. However, you can most likely use any release action of your choosing.
    #   # https://github.com/ncipollo/release-action
    # - name: create release
    #   uses: ncipollo/release-action@v1.14.0
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     generateReleaseNotes: true
    #     tag: ${{ github.ref_name }}
    #     artifacts: ${{ steps.export.outputs.archive_directory }}/*
